asn: 65013
loopback: 10.0.0.3
vtep: 10.0.0.3
evpn_mh:
  interface: to_host2
  es_sys_mac: "44:38:39:ff:ff:01"
  es_id: 100
p2p_links:
  - {local_if: to_spine1, peer_ip: "10.255.0.4", peer_asn: 65000, peer_name: spine1}
  - {local_if: to_spine2, peer_ip: "10.255.0.10", peer_asn: 65000, peer_name: spine2}
